# Shared/OnchainKit variables
# https://www.drvnvhcls.app
NEXT_PUBLIC_PROJECT_NAME=
NEXT_PUBLIC_URL=http://localhost:3000
NEXT_PUBLIC_ONCHAINKIT_API_KEY=
NEXT_PUBLIC_ONCHAINKIT_PROJECT_ID=
# NEXT_PUBLIC_ICON_URL=


# Redis config
REDIS_URL=
REDIS_TOKEN=

#MongoDB Database
MONGODB_URI=
ENCRYPTION_KEY=

# IPFS Configuration
NEXT_PUBLIC_PINATA_API_KEY=
NEXT_PUBLIC_PINATA_SECRET_KEY=
PINATA_JWT=
NEXT_PUBLIC_IPFS_GATEWAY=

# Reown Wallet Key
NEXT_PUBLIC_PROJECT_ID=

# Alchemy API Key
ALCHEMY_API_KEY=
NEXT_PUBLIC_BASE_RPC_URL=

# Buster Token Variables
NEXT_PUBLIC_BSTR_CONTRACT_ADDRESS=
NEXT_PUBLIC_BSTR_ETH_POOL_ADDRESS=
NEXT_PUBLIC_BSTR_USDC_POOL_ADDRESS=