"use client";

import { X, DollarSign, Users, Gift, Star, Crown, Zap } from "lucide-react";
import Image from "next/image";

interface BenefitsModalProps {
  isOpen: boolean;
  onClose: () => void;
  keyType: "steel" | "carbon" | "titanium";
}

const keyData = {
  steel: {
    name: "Steel Key Member",
    price: "$450 USDC",
    supply: "62 keys",
    color: "from-gray-600 to-gray-700",
    textColor: "text-gray-300",
    icon: "Steel.gif",
    benefits: [
      "Lifetime DRVN Culture premium membership & Presale access to every tokenized vehicle release",
      "0.1 $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 500K $BSTR airdrop + Recurring $BSTR rewards",
      "A chance to win 1 full car share every time a vehicle is added to our collection",
      "DRVN Founder's Club phygital* hat",
      "DRVN PFP Airdrop – Uncommon (coming soon)",
    ],
  },
  carbon: {
    name: "Carbon Key Member",
    price: "$1,100 USDC",
    supply: "24 keys",
    color: "from-green-600 to-green-700",
    textColor: "text-green-300",
    icon: "Carbon.gif",
    benefits: [
      "All Steel level benefits, plus…",
      "0.25 $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 1.25M $BSTR airdrop + Recurring $BSTR rewards",
      "VIP Presale access to every tokenized vehicle release",
      "DRVN Founder's Club phygital* jacket",
      "DRVN PFP Airdrop – Rare (coming soon)",
    ],
  },
  titanium: {
    name: "Titanium Key Member",
    price: "$4,000 USDC",
    supply: "7 keys",
    color: "from-blue-600 to-blue-700",
    textColor: "text-blue-300",
    icon: "Titanium.gif",
    benefits: [
      "All Carbon level benefits, plus…",
      "1 full $RS1 Ferrari 360 Modena RWA share (of only 64 total shares)",
      "Instant 4.75M $BSTR airdrop + Recurring $BSTR rewards",
      "Profit share on all revenue generated by the $RS1 Ferrari",
      "Exclusive $RS1 Ferrari phygital* merch",
      "Custom Key to the Ferrari",
      "Custom Titanium Club watch",
      "Titanium Club jacket",
      "DRVN PFP Airdrop – Legendary (coming soon)",
    ],
  },
};

export function BenefitsModal({ isOpen, onClose, keyType }: BenefitsModalProps) {
  if (!isOpen) return null;

  const data = keyData[keyType];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose} />

      {/* Modal Content */}
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <div className="overflow-hidden rounded-xl outline -outline-offset-1 outline-white/10 bg-gray-950">
          {/* Header */}
          <div className="relative px-6 py-5 border-b border-white/10">
            <button
              onClick={onClose}
              className="absolute top-4 right-4 p-2 hover:bg-white/10 rounded-full transition-colors cursor-pointer"
            >
              <X className="w-5 h-5 text-gray-400" />
            </button>

            <div className="flex items-center gap-4 mb-4">
              <div
                className={`w-16 h-16 rounded-xl overflow-hidden bg-linear-to-r ${data.color} ring-1 ring-white/10`}
              >
                <Image
                  src={`/Cars/${data.icon}`}
                  alt={`${data.name} Key`}
                  width={64}
                  height={64}
                  className="w-full h-full object-cover"
                  unoptimized
                />
              </div>
              <div className="flex-1 min-w-0">
                <h2 className="text-2xl font-bold text-white font-mono mb-3">{data.name}</h2>
                <dl className="-my-3 divide-y divide-white/10 text-sm/6">
                  <div className="flex justify-between gap-x-4 py-3">
                    <dt className="flex items-center gap-2 text-gray-400 font-mono">
                      <DollarSign className="w-4 h-4 text-[#00daa2]" />
                      Price
                    </dt>
                    <dd className="font-medium text-[#00daa2] font-mono">{data.price}</dd>
                  </div>
                  <div className="flex justify-between gap-x-4 py-3">
                    <dt className="flex items-center gap-2 text-gray-400 font-mono">
                      <Users className="w-4 h-4 text-white/60" />
                      Supply
                    </dt>
                    <dd className="font-medium text-white font-mono">{data.supply}</dd>
                  </div>
                </dl>
              </div>
            </div>
          </div>

          {/* Benefits Section */}
          <div className="px-6 py-5">
            <div className="flex items-center gap-2 mb-6">
              <Gift className="w-6 h-6 text-yellow-500" />
              <h3 className="text-xl font-bold text-white font-mono">Member Benefits</h3>
            </div>

            <div className="space-y-4">
              {data.benefits.map((benefit, index) => (
                <div
                  key={index}
                  className="flex items-start gap-3 p-4 bg-white/5 rounded-lg border border-white/10"
                >
                  <div className="shrink-0 mt-1">
                    {index === 0 && keyType !== "steel" ? (
                      <Crown className="w-5 h-5 text-yellow-500" />
                    ) : (
                      <Star className="w-5 h-5 text-yellow-500" />
                    )}
                  </div>
                  <p className="text-gray-300 font-mono text-sm leading-relaxed">{benefit}</p>
                </div>
              ))}
            </div>

            {/* Footer */}
            <div className="mt-8 pt-6 border-t border-white/10">
              <div className="flex items-center justify-center gap-2 text-sm text-gray-400 font-mono">
                <Zap className="w-4 h-4" />
                <span>Limited Supply • Exclusive Access • Premium Benefits</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
